// <auto-generated />
namespace Fmi.OpenMinds.FitChallenge.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RankModelUpdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RankModelUpdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201506061752157_RankModelUpdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
